remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: "Nischay"
logo: "nischay.jpg"
description: "Nullius in verba"

url: "https://nischay1.github.io" 
plugins:
  - jekyll-sitemap



google_analytics: G-YWBWTRZX5Z
